name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-node-services:
    name: Test Node.js Microservices
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - company-service
          - entretien-service
          - notification-service
          - user-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm install

      - name: Run unit and integration tests
        run: |
          cd ${{ matrix.service }}
          if [ -f jest.config.js ]; then
            if [ -d tests/unit ]; then npx jest tests/unit --ci; fi
            if [ -d tests/integration ]; then npx jest tests/integration --ci; fi
          fi

  test-python-cv-matching:
    name: Test Python cv-matching-service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cv-matching-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.0'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/unit